// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIU9OBGdH7qiPKTdxDct8ZnnDqsSRvRXk',
    appId: '1:821410609040:web:f8db7c40029be598192515',
    messagingSenderId: '821410609040',
    projectId: 'kuriftu-9d6e8',
    authDomain: 'kuriftu-9d6e8.firebaseapp.com',
    databaseURL: 'https://kuriftu-9d6e8-default-rtdb.firebaseio.com',
    storageBucket: 'kuriftu-9d6e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgcKqEYMwmSgl_ZBsReD4W6vCNS9lUdQk',
    appId: '1:821410609040:android:79767399fd4e1098192515',
    messagingSenderId: '821410609040',
    projectId: 'kuriftu-9d6e8',
    databaseURL: 'https://kuriftu-9d6e8-default-rtdb.firebaseio.com',
    storageBucket: 'kuriftu-9d6e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhZOZ2FCOs8SC1i05yKZ3YIXgO-hjXKcU',
    appId: '1:821410609040:ios:8d6ba8c2d015079f192515',
    messagingSenderId: '821410609040',
    projectId: 'kuriftu-9d6e8',
    databaseURL: 'https://kuriftu-9d6e8-default-rtdb.firebaseio.com',
    storageBucket: 'kuriftu-9d6e8.appspot.com',
    iosBundleId: 'com.example.kuriftuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhZOZ2FCOs8SC1i05yKZ3YIXgO-hjXKcU',
    appId: '1:821410609040:ios:a9f3976e53f91556192515',
    messagingSenderId: '821410609040',
    projectId: 'kuriftu-9d6e8',
    databaseURL: 'https://kuriftu-9d6e8-default-rtdb.firebaseio.com',
    storageBucket: 'kuriftu-9d6e8.appspot.com',
    iosBundleId: 'com.example.kuriftuApp.RunnerTests',
  );
}
